### PR TITLE
update_engine: Stop using deprecated curl options and info names

### PR DESCRIPTION
**Pull request by krnowak**
The CURLOPT_PROTOCOLS, CURLOPT_REDIR_PROTOCOLS option the CURLINFO_CONTENT_LENGTH_DOWNLOAD info name are deprecated, but fortunately they have straightforward replacements.

CI: http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/554/cldsv/

It's pulled in by weekly updates: https://github.com/flatcar/coreos-overlay/pull/2404.

### CODE REVIEW

**Comment by krnowak** [comment]
CI with this version passed.

**Comment by krnowak** [comment]
Do we need a changelog entry for these changes?

**Comment by pothos** [comment]
> Do we need a changelog entry for these changes?

Not really, this is an internal change that requires no user action. (We could also change the PR template and limit the changelog checkbox to only show up in the coreos-overlay/portage-stable/scripts repos because here it is useless.)

**Review by pothos — APPROVED** [review]

**Comment by krnowak** [comment]
Fixed grammar in the commit message. Thanks for the review.

**Pull request merged**
